### ISSUE TITLE
Accounts.yml is too large to load

### ISSUE THREAD

**Issue by SiuanSong** [myth-MC/banco#46]
Banco Version 0.6.5
Purpur 1.21.1 #2306

It appears that my accounts.yml file is too large for the plugin to load and so the plugin just disables upon restart. I'm not sure where exactly it's pulling the player info from, but it's pulled about 40k UUIDs. (This is in line with our Essentials user data, which is about 58k users. So it's probably not some random thing it's doing. Just for clarity.)

[Startup Log/Error](https://pastebin.com/P8b5Y6PD)

**Comment by U8092** [comment]
Hey, @SiuanSong!

What is the size of your accounts.yml file? You can find it in `/plugins/banco/accounts.yml`.
At first glance, this looks to me like an issue inside the file itself (could very well be an account that has been corrupted while saving data). I'm willing to take a close look at the file, if you're okay with that. Since it contains sensitive data (UUIDs and accounts balance) you can contact me via email at uisl8092@gmail.com or reach me on Discord at @u8092.

I can also provide instructions to you or your team members if that works better. Please let me know your thoughts on this!

**Comment by SiuanSong** [comment]
Sent ya a friend request on discord!
